const products = [
  {
    ID: 1,
    CATEGORY: 'Cold and Flu',
    BRAND: 'Vicks',
    TYPE: 'Vaporub',
    QTY: '100g',
    SPRICE: 4.5,
    PPRICE: 3.7,
    STOCK: 15,
    LIMIT: 0
  },
  {
    ID: 2,
    CATEGORY: 'Cold and Flu',
    BRAND: 'Vicks',
    TYPE: 'First Defence',
    QTY: '15ml',
    SPRICE: 6.8,
    PPRICE: 5,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 3,
    CATEGORY: 'Cold and Flu',
    BRAND: 'Gsk',
    TYPE: 'Night Nurse',
    QTY: '160ml',
    SPRICE: 9,
    PPRICE: 7.5,
    STOCK: 30,
    LIMIT: 0
  },
  {
    ID: 4,
    CATEGORY: 'Cold and Flu',
    BRAND: 'Lemsip',
    TYPE: 'Max',
    QTY: '16 caps',
    SPRICE: 4.2,
    PPRICE: 3.7,
    STOCK: 25,
    LIMIT: 0
  },
  {
    ID: 5,
    CATEGORY: 'Cold and Flu',
    BRAND: 'Lemsip',
    TYPE: 'Standard',
    QTY: '10 sachets',
    SPRICE: 4.5,
    PPRICE: 3.5,
    STOCK: 25,
    LIMIT: 0
  },
  {
    ID: 6,
    CATEGORY: 'Cold and Flu',
    BRAND: 'Sudafed',
    TYPE: 'Day and Night',
    QTY: '16 caps',
    SPRICE: 4.5,
    PPRICE: 3.2,
    STOCK: 30,
    LIMIT: 1
  },
  {
    ID: 7,
    CATEGORY: 'Cold and Flu',
    BRAND: 'Sudafed',
    TYPE: 'Max',
    QTY: '16 caps',
    SPRICE: 4.2,
    PPRICE: 3.2,
    STOCK: 30,
    LIMIT: 1
  },
  {
    ID: 8,
    CATEGORY: 'Cold and Flu',
    BRAND: 'Benylin',
    TYPE: 'Mucus relief',
    QTY: '16 caps',
    SPRICE: 4.8,
    PPRICE: 3.2,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 9,
    CATEGORY: 'Cold and Flu',
    BRAND: 'Benylin',
    TYPE: '4 flu',
    QTY: '24 caps',
    SPRICE: 6,
    PPRICE: 4.9,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 10,
    CATEGORY: 'Skincare',
    BRAND: 'E45',
    TYPE: 'Psoriasis cream',
    QTY: '50ml',
    SPRICE: 20,
    PPRICE: 16,
    STOCK: 15,
    LIMIT: 0
  },
  {
    ID: 11,
    CATEGORY: 'Skincare',
    BRAND: 'Eurax',
    TYPE: 'Skin cream',
    QTY: '100g',
    SPRICE: 5.7,
    PPRICE: 4.2,
    STOCK: 15,
    LIMIT: 0
  },
  {
    ID: 12,
    CATEGORY: 'Skincare',
    BRAND: 'Eucerin',
    TYPE: 'Skin relief cream',
    QTY: '50ml',
    SPRICE: 9,
    PPRICE: 7,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 13,
    CATEGORY: 'Skincare',
    BRAND: 'Eucerin',
    TYPE: 'Face scrub',
    QTY: '100ml',
    SPRICE: 7.5,
    PPRICE: 6,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 14,
    CATEGORY: 'Skincare',
    BRAND: 'Dermalex',
    TYPE: 'Psoriasis cream',
    QTY: '150ml',
    SPRICE: 30,
    PPRICE: 25,
    STOCK: 10,
    LIMIT: 0
  },
  {
    ID: 15,
    CATEGORY: 'Skincare',
    BRAND: 'Dermalex',
    TYPE: 'Repair and Restore',
    QTY: '100g',
    SPRICE: 12,
    PPRICE: 10,
    STOCK: 10,
    LIMIT: 0
  },
  {
    ID: 16,
    CATEGORY: 'Skincare',
    BRAND: 'Dermalex',
    TYPE: 'Eczema cream',
    QTY: '30g',
    SPRICE: 12,
    PPRICE: 9.7,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 17,
    CATEGORY: 'Skincare',
    BRAND: 'Dermalex',
    TYPE: 'Eczema cream',
    QTY: '100g',
    SPRICE: 25,
    PPRICE: 22.2,
    STOCK: 5,
    LIMIT: 0
  },
  {
    ID: 18,
    CATEGORY: 'Skincare',
    BRAND: 'Cetaphil',
    TYPE: 'Moisturising cream',
    QTY: '50ml',
    SPRICE: 10,
    PPRICE: 7.6,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 19,
    CATEGORY: 'Skincare',
    BRAND: 'Cetaphil',
    TYPE: 'Exfoliating cleanser',
    QTY: '180ml',
    SPRICE: 12,
    PPRICE: 10.1,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 20,
    CATEGORY: 'Headaches and pain relief',
    BRAND: 'Nurofen',
    TYPE: 'Meltlets',
    QTY: '16 caps',
    SPRICE: 4,
    PPRICE: 3.7,
    STOCK: 40,
    LIMIT: 0
  },
  {
    ID: 21,
    CATEGORY: 'Headaches and pain relief',
    BRAND: 'Nurofen',
    TYPE: 'Express',
    QTY: '16 caps',
    SPRICE: 4,
    PPRICE: 3.5,
    STOCK: 30,
    LIMIT: 0
  },
  {
    ID: 22,
    CATEGORY: 'Headaches and pain relief',
    BRAND: 'Nurofen',
    TYPE: 'Max strength',
    QTY: '32 caps',
    SPRICE: 7,
    PPRICE: 6.2,
    STOCK: 25,
    LIMIT: 0
  },
  {
    ID: 23,
    CATEGORY: 'Headaches and pain relief',
    BRAND: 'Nurofen',
    TYPE: 'Standard',
    QTY: '16 caps',
    SPRICE: 4,
    PPRICE: 3.2,
    STOCK: 30,
    LIMIT: 0
  },
  {
    ID: 24,
    CATEGORY: 'Headaches and pain relief',
    BRAND: 'Cuprofen ',
    TYPE: 'Max strength',
    QTY: '96 caps',
    SPRICE: 11,
    PPRICE: 9,
    STOCK: 20,
    LIMIT: 1
  },
  {
    ID: 25,
    CATEGORY: 'Headaches and pain relief',
    BRAND: 'Solpadeine',
    TYPE: 'Headache',
    QTY: '16 caps',
    SPRICE: 2,
    PPRICE: 1.6,
    STOCK: 20,
    LIMIT: 1
  },
  {
    ID: 26,
    CATEGORY: 'Headaches and pain relief',
    BRAND: 'Anadin',
    TYPE: 'Extra',
    QTY: '16 caps',
    SPRICE: 2.3,
    PPRICE: 2,
    STOCK: 30,
    LIMIT: 1
  },
  {
    ID: 27,
    CATEGORY: 'Headaches and pain relief',
    BRAND: 'Anadin',
    TYPE: 'Triple action',
    QTY: '12 caps',
    SPRICE: 2,
    PPRICE: 1.9,
    STOCK: 30,
    LIMIT: 1
  },
  {
    ID: 28,
    CATEGORY: 'Headaches and pain relief',
    BRAND: 'Anadin',
    TYPE: 'Original',
    QTY: '16 caps',
    SPRICE: 1.8,
    PPRICE: 1.5,
    STOCK: 30,
    LIMIT: 1
  },
  {
    ID: 29,
    CATEGORY: 'Headaches and pain relief',
    BRAND: 'Disprin',
    TYPE: 'Soluble',
    QTY: '32 tablets',
    SPRICE: 3.6,
    PPRICE: 2.8,
    STOCK: 20,
    LIMIT: 1
  },
  {
    ID: 30,
    CATEGORY: 'Digestion',
    BRAND: 'Dioralyte',
    TYPE: 'Blackcurrant',
    QTY: '12 sachets',
    SPRICE: 8,
    PPRICE: 7.3,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 31,
    CATEGORY: 'Digestion',
    BRAND: 'Dioralyte',
    TYPE: 'Lemon',
    QTY: '12 sachets',
    SPRICE: 8,
    PPRICE: 7.3,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 32,
    CATEGORY: 'Digestion',
    BRAND: 'Gaviscon',
    TYPE: 'Chewable',
    QTY: '24 tablets',
    SPRICE: 4.2,
    PPRICE: 3.5,
    STOCK: 25,
    LIMIT: 0
  },
  {
    ID: 33,
    CATEGORY: 'Digestion',
    BRAND: 'Senokot',
    TYPE: 'Max',
    QTY: '10 tablets',
    SPRICE: 3,
    PPRICE: 2.7,
    STOCK: 10,
    LIMIT: 0
  },
  {
    ID: 34,
    CATEGORY: 'Digestion',
    BRAND: 'Gaviscon',
    TYPE: 'Advance',
    QTY: '300ml',
    SPRICE: 10,
    PPRICE: 8.1,
    STOCK: 10,
    LIMIT: 0
  },
  {
    ID: 35,
    CATEGORY: 'Allergy',
    BRAND: 'Benadryl',
    TYPE: 'Relief',
    QTY: '24 caps',
    SPRICE: 9,
    PPRICE: 7.1,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 36,
    CATEGORY: 'Allergy',
    BRAND: 'Piriteze',
    TYPE: 'tabs',
    QTY: '7 tablets',
    SPRICE: 3,
    PPRICE: 2.3,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 37,
    CATEGORY: 'Allergy',
    BRAND: 'Beconase',
    TYPE: 'Relief',
    QTY: '100 sprays',
    SPRICE: 6,
    PPRICE: 4,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 38,
    CATEGORY: 'First aid',
    BRAND: 'Dettol',
    TYPE: 'Antiseptic',
    QTY: '500ml',
    SPRICE: 3.2,
    PPRICE: 3,
    STOCK: 20,
    LIMIT: 0
  },
  {
    ID: 39,
    CATEGORY: 'First aid',
    BRAND: 'Dettol',
    TYPE: 'Hand sanitizer',
    QTY: '500ml',
    SPRICE: 7,
    PPRICE: 6.3,
    STOCK: 50,
    LIMIT: 0
  },
  {
    ID: 40,
    CATEGORY: 'First aid',
    BRAND: 'Elastoplast',
    TYPE: 'plasters',
    QTY: '20 plasters',
    SPRICE: 3,
    PPRICE: 2,
    STOCK: 30,
    LIMIT: 0
  },
  {
    ID: 41,
    BRAND: 'TCP',
    TYPE: 'Liquid',
    QTY: '200ml',
    SPRICE: 4,
    PPRICE: 3.2,
    STOCK: 20,
    LIMIT: 0
  }
]

export default products;